# Generated by Django 5.0.3 on 2024-04-10 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_shop_products_shop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='shop_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='courses.shop'),
        ),
    ]
