# Generated by Django 5.0.3 on 2024-04-13 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_products_shop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, default=(('user', 'User'), ('admin', 'Admin'), ('employee', 'Employee'), ('seller', 'Seller')), null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.userrole'),
        ),
    ]
