# Generated by Django 5.0.3 on 2024-04-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('employee', 'Employee'), ('seller', 'Seller')], max_length=50, null=True),
        ),
    ]
