# Generated by Django 5.0.3 on 2024-04-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_user_role_alter_userrole_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRole',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('employee', 'Employee'), ('seller', 'Seller')], max_length=50, null=True),
        ),
    ]
