# Generated by Django 4.2.11 on 2024-05-31 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_set', to='courses.products'),
        ),
    ]
