# Generated by Django 5.0.3 on 2024-04-21 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_delete_userrole_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='tags',
        ),
    ]
