# Generated by Django 4.2.11 on 2024-06-10 10:37

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_shop_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_proof',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='statusPayment',
            field=models.CharField(choices=[('Đang chờ xử lý', 'Đang xử lý'), ('Không thể xử lý', 'Thất Bại'), ('Đã đăng ký', 'Thành Công')], default='Đang chờ xử lý', max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orders',
            name='paymentMethod',
            field=models.CharField(choices=[('Chuyển khoản Ngân Hàng', 'Chuyển khoản Ngân Hàng'), ('Chuyển khoản Momo', 'Chuyển khoản MoMo')], max_length=50, null=True),
        ),
    ]
