# Generated by Django 4.2.11 on 2024-06-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_orders_payment_proof_orders_statuspayment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='discount',
            field=models.IntegerField(),
        ),
    ]
