# Generated by Django 4.2.11 on 2024-06-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_orders_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='orders',
            name='totalPrice',
            field=models.IntegerField(),
        ),
    ]
