# Generated by Django 4.2.11 on 2024-06-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_orders_discount_alter_orders_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='paymentMethod',
            field=models.CharField(choices=[('COD', 'Thanh toán khi nhận hàng'), ('MOMO', 'Ví điện tử Momo')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='statusPayment',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DENY', 'Deny'), ('DONE', 'Done')], max_length=50),
        ),
    ]
